version: "3.9"

services:
  web:
    build: .
    command: >
      sh -c "gunicorn pna.wsgi:application --bind 0.0.0.0:${WEB_PORT}"
    volumes:
      - .:/app
    ports:
      - "${WEB_PORT}:${WEB_PORT}"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    env_file:
      - .env

volumes:
  postgres_data:
