# Generated by Django 5.1.5 on 2025-09-06 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_question_marks_question_negative_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_reports', to='api.student'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('non-coding', 'Non Coding')], default='non-coding', max_length=255),
        ),
        migrations.AlterField(
            model_name='report',
            name='assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.assessmentassignment'),
        ),
        migrations.AlterField(
            model_name='report',
            name='candidate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidate_reports', to=settings.AUTH_USER_MODEL),
        ),
    ]
