# Generated by Django 5.1.5 on 2025-10-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_add_student_to_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('coding', 'Coding'), ('non-coding', 'Non Coding (MCQ)')], default='non-coding', max_length=20),
        ),
    ]
